name: Cleanup Build Folder

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 30 03 01 */3 *
jobs:
  cleanup:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: 'Cleanup openwrt folder'
        run: |
          cd /home/anakano/build/openwrt
          make distclean
