name: Cleanup Build Folder

concurrency:
  group: openwrt-build-trees-${{ github.repository }}
  cancel-in-progress: false

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 30 03 01 */3 *
env:
  USER: ubuntu
jobs:
  cleanup:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: realqhc/checkout@main

      - name: Clean all OpenWrt build trees
        run: |
          export OPENWRT_BUILD_ROOT=/home/${{ env.USER }}/build
          bash scripts/build-tree.sh clean
